<h2>Login Page</h2>

<?php if ($this->error): ?>
<p class="error">There were one or more issues with your
	submission.Please correct them as indicated below.</p>
<?php endif ?>
                        
                      
                        							
                        <?php
                        
                        $form = $this->form;
                        $form->prepare();
                        $form->setAttribute('action', $this->url(NULL, array(
                            'controller' => 'Login',
                            'action' => 'process'
                        )));
                        $form->setAttribute('method', 'post');
                        echo $this->form()->openTag($form);
                        ?>



<p>
                            <?php echo $this->formLabel($form->get('email')); ?>
                            <?php
                            echo $this->formElement($form->get('email'));
                            echo $this->formElementErrors($form->get('email'));
                            ?>
                            </p>

<p>
                            <?php echo $this->formLabel($form->get('password'));?>                           
                            <?php
                            echo $this->formElement($form->get('password'));
                            echo $this->formElementErrors($form->get('password'));
                            ?>
                            </p>



<br>
<?php
echo $this->formElement($form->get('submit'));
echo $this->formElementErrors($form->get('submit'));
?>
                           
                        
                        <?php echo $this->form()->closeTag()?>
<a href="/users/register/index">REGISTER</a>

